[experiment]
benchmark = "cstr"
base_seed = 20250605
time_limit = 3600
modes = ["solve", "root"]
root_time_limit = 600
relaxation_time_limit = 600

[instances]
NT = [2, 3, 4, 5, 6, 7, 8, 9, 10]

[[strategies]]
name = "gdp.bigm"
label = "bigm"

[[strategies]]
name = "gdp.mbigm"
label = "mbigm"

[[strategies]]
name = "gdp.binary_multiplication"
label = "binmult"

[[strategies]]
name = "gdp.hull"
label = "hull"

[[strategies]]
name = "gdp.hull_exact"
label = "GEHR"

[[solvers]]
name = "gams"
subsolver = "gurobi"

[[solvers]]
name = "gams"
subsolver = "scip"
